### ISSUE TITLE
Problem with levels where deadlock is possible

### ISSUE THREAD

**Issue by MennoK** [jeroentempels/BlockAndRollSolver#1]
I think there is still a problem with solving levels where deadlocks are possible (e.g. after a wrong move is made, the level isn't solvable anymore).

``` java
 boolean[][] field = {
                {true, true, true},
                {true, true, true},
                {true, true, true},
        };

        BoardBuilder builder = new BoardBuilder(field);

        builder.addBlock(2, 0, false, true, false, false);
        builder.addBlock(1, 1, false, true, false, true);
        builder.addBlock(0, 2, false, false, true, true);

        builder.addBird(2, 0);

        Solver.solve(builder.toBoard(), 2, 2, Direction.DOWN).forEach(System.out::println);
```

This level is solvable in the moves: UP, RIGHT, DOWN or DOWN, RIGHT. But a deadlock occurs when the first move is LEFT or RIGHT.

The output of the solver gives:

``` java
       RIGHT
```

**Comment by jeroentempels** [comment]
Dear MennoK,

I think there is an error in your modeling of the field. I worked out this example on paper and found that just moving right is the correct solution. Maybe the readme was unclear about how to model the game. There are only blocks on the anti-diagonal of the field and the bird is located in the block at the lower left corner of the field. Swiping right moves this block to the lower right corner which is the goal position. The block has no wall on the south side, so the solution is correct.

**Comment by MennoK** [comment]
Hi, 

You are right. I used the wrong presentation for the walls. The blocks I wanted to add were:

``` java
        builder.addBlock(2, 0, true, false, true, true);
        builder.addBlock(1, 1, true, false, true, false);
        builder.addBlock(0, 2, true, true, false, false);
```

And this will give the right solution. Thanks!
